// Demo mode flag utility
export const isDemoMode = () => import.meta.env.VITE_DEMO_MODE === 'true';

// Example demo data for key entities
export const DEMO_DATA = {
  dashboard: {
    revenue: 120000,
    expenses: 45000,
    profit: 75000,
    invoicesCount: 42,
    usersCount: 8,
    companiesCount: 3,
    // ...add more as needed
  },
  invoices: [
    { id: 1, number: 'INV-1001', amount: 1200, status: 'paid', date: '2025-12-01' },
    { id: 2, number: 'INV-1002', amount: 800, status: 'unpaid', date: '2025-12-05' },
  ],
  users: [
    { id: 1, name: 'Demo User', email: 'demo@smartaccounting.com', role: 'admin' },
    { id: 2, name: 'Accountant', email: 'accountant@smartaccounting.com', role: 'accountant' },
  ],
  companies: [
    { id: 1, name: 'Demo GmbH', country: 'Germany' },
    { id: 2, name: 'Test AG', country: 'Germany' },
  ],
  expenses: [
    {
      id: 'exp-1001',
      number: 'EXP-1001',
      date: '2025-11-05',
      description: 'Compliance consultancy workshop',
      amount: 420.75,
      currency: 'EUR',
      vendor: 'Berlin Advisory GmbH',
      category: 'services',
      vatRate: 19,
      vatAmount: 67.84,
    },
    {
      id: 'exp-1002',
      number: 'EXP-1002',
      date: '2025-11-12',
      description: 'Cloud accounting platform renewal',
      amount: 995.5,
      currency: 'EUR',
      vendor: 'CloudBooks AG',
      category: 'software',
      vatRate: 19,
      vatAmount: 159.13,
    },
  ],
  aiInsights: [
    {
      id: 'insight-1',
      type: 'Overdue invoice',
      summary: 'Invoice INV-1002 is overdue by 18 days with no payment dates.',
      severity: 'high',
      confidenceScore: 0.92,
      confidence: 0.92,
      relatedEntity: 'Invoice INV-1002',
      explanation:
        'Historically, this customer pays within 10 days. Recommend sending a reminder before the next reporting cycle.',
      advisory: true,
    },
    {
      id: 'insight-2',
      type: 'Expense anomaly',
      summary: 'Vendor Berlin Advisory GmbH submitted three invoices in the same week.',
      severity: 'medium',
      confidenceScore: 0.75,
      confidence: 0.75,
      relatedEntity: 'Vendor: Berlin Advisory GmbH',
      explanation:
        'Multiple similar services posted 48 hours apart—validate that these are distinct deliverables.',
      advisory: true,
    },
  ],
  bankStatements: [
    {
      id: 'demo-stmt-1',
      account: 'DE98 7654 3210 1234 5678 90',
      balance: 56120,
      date: '2025-11-30',
      fileName: 'Demo Statement • November',
      totalTransactions: 12,
      processedTransactions: 12,
      statementPeriodStart: '2025-11-01',
      statementPeriodEnd: '2025-11-30',
      importDate: '2025-11-30T08:40:00Z',
      status: 'COMPLETED',
    },
    {
      id: 'demo-stmt-2',
      account: 'DE22 1111 2222 3333 4444 55',
      balance: 48200,
      date: '2025-12-01',
      fileName: 'Live Import • December',
      totalTransactions: 8,
      processedTransactions: 5,
      statementPeriodStart: '2025-12-01',
      statementPeriodEnd: '2025-12-05',
      importDate: '2025-12-01T10:12:00Z',
      status: 'PROCESSING',
    },
  ],
  bankStatementTransactions: {
    'demo-stmt-1': [
      {
        id: 'txn-1',
        transactionDate: '2025-11-05',
        description: 'Payment received from Müller GmbH',
        amount: 2450,
        currency: 'EUR',
        category: 'SALES',
        isReconciled: true,
      },
      {
        id: 'txn-2',
        transactionDate: '2025-11-18',
        description: 'Berlin Advisory GmbH consulting',
        amount: -420.75,
        currency: 'EUR',
        category: 'EXPENSES',
        isReconciled: false,
      },
      {
        id: 'txn-3',
        transactionDate: '2025-11-22',
        description: 'CloudBooks subscription',
        amount: -995.5,
        currency: 'EUR',
        category: 'EXPENSES',
        isReconciled: true,
      },
      {
        id: 'txn-4',
        transactionDate: '2025-11-29',
        description: 'Interest income',
        amount: 150,
        currency: 'EUR',
        category: 'OTHER',
        isReconciled: false,
      },
    ],
    'demo-stmt-2': [
      {
        id: 'txn-5',
        transactionDate: '2025-12-01',
        description: 'Müller GmbH partial payment',
        amount: 1200,
        currency: 'EUR',
        category: 'SALES',
        isReconciled: false,
      },
      {
        id: 'txn-6',
        transactionDate: '2025-12-02',
        description: 'Travel advance reimbursement',
        amount: -350.25,
        currency: 'EUR',
        category: 'EXPENSES',
        isReconciled: false,
      },
      {
        id: 'txn-7',
        transactionDate: '2025-12-03',
        description: 'Office rent',
        amount: -1200,
        currency: 'EUR',
        category: 'EXPENSES',
        isReconciled: false,
      },
    ],
    default: [
      {
        id: 'txn-demo-1',
        transactionDate: '2025-11-15',
        description: 'Demo payment received',
        amount: 1800,
        currency: 'EUR',
        category: 'SALES',
        isReconciled: false,
      },
    ],
  },
  bankStatementAuditLogs: {
    'demo-stmt-1': [
      {
        id: 'audit-1',
        action: 'bank_transaction_reconciled',
        resourceId: 'txn-1',
        timestamp: '2025-11-30T10:15:00Z',
        user: { firstName: 'Anna', lastName: 'Schmidt', email: 'anna@demo.com', role: 'accountant' },
        reason: 'Matched to Invoice INV-1001',
        newValues: {
          metadata: {
            targetType: 'invoice',
            targetId: 'INV-1001',
          },
        },
      },
      {
        id: 'audit-2',
        action: 'bank_transaction_reconciled',
        resourceId: 'txn-3',
        timestamp: '2025-11-30T11:20:00Z',
        user: { firstName: 'Markus', lastName: 'Weber', email: 'markus@demo.com', role: 'admin' },
        reason: 'CloudBooks subscription auto-matched',
        newValues: {
          metadata: {
            targetType: 'expense',
            targetId: 'EXP-1002',
          },
        },
      },
    ],
    default: [
      {
        id: 'audit-demo-1',
        action: 'bank_transaction_reconciliation_undone',
        resourceId: 'txn-demo-1',
        timestamp: '2025-11-25T09:00:00Z',
        user: { firstName: 'Claudia', lastName: 'Meier', email: 'claudia@demo.com', role: 'accountant' },
        reason: 'Need to revalidate vendor details',
        newValues: {
          metadata: {
            targetType: 'expense',
            targetId: 'EXP-1001',
          },
        },
      },
    ],
  },
};
