FROM node:20-bullseye

WORKDIR /usr/src/app

ENV NODE_ENV=development

RUN apt-get update && apt-get install -y \
  python3 \
  make \
  g++ \
  curl \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN mkdir -p logs uploads temp

EXPOSE 5000

CMD ["node", "index.js"]