import React from 'react';
import { AIBadge } from './AIBadge';
import AISeverityPill from './AISeverityPill';
import AIMetadataLine from './AIMetadataLine';
import { truncateText } from '../lib/utils/formatting';

const confidenceColors = {
  high: 'bg-green-100 text-green-800',
  medium: 'bg-yellow-100 text-yellow-800',
  low: 'bg-red-100 text-red-800',
};

function AIInsightCard({
  type,
  summary,
  confidence,
  confidenceScore,
  why,
  ExplainWhy,
  severity,
  dataSource,
  lastEvaluated,
  whyMatters,
}) {
  const resolvedWhyMatters = truncateText(whyMatters || summary || 'Review this insight.', 120);
  const resolvedConfidence =
    typeof confidenceScore === 'number'
      ? confidenceScore
      : typeof confidence === 'number'
        ? confidence
        : confidence;
  const hasConfidence = resolvedConfidence !== null && resolvedConfidence !== undefined;
  return (
    <section
      className="border rounded-lg shadow-sm p-5 bg-white transition-all duration-300"
      role="region"
      aria-label="AI-generated insight card"
      tabIndex={0}
    >
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <AIBadge label="AI-generated" tooltip="This insight is generated by AI." />
          <span
            className="text-sm font-semibold text-blue-700 uppercase tracking-wide"
            id="ai-insight-label"
          >
            AI Insight
          </span>
        </div>
        <AISeverityPill severity={severity} />
      </div>
      {hasConfidence ? (
        <span
          className={`px-2 py-1 rounded text-xs font-medium ${confidenceColors[resolvedConfidence] || 'bg-gray-100 text-gray-700'}`}
          aria-label={`Confidence: ${resolvedConfidence}`}
        >
          Confidence:{' '}
          {typeof resolvedConfidence === 'string'
            ? `${resolvedConfidence.charAt(0).toUpperCase()}${resolvedConfidence.slice(1)}`
            : `${Math.round(resolvedConfidence * 100)}%`}
        </span>
      ) : null}
      <div className="mb-2">
        <span className="font-bold" aria-label="Insight type">
          {type}
        </span>
        <p className="mt-1 text-gray-800" aria-live="polite">
          {summary}
        </p>
      </div>
      <AIMetadataLine
        whyMatters={resolvedWhyMatters}
        dataSource={dataSource}
        lastEvaluated={lastEvaluated}
        className="mb-2"
      />
      <div aria-label="AI insight context">
        <ExplainWhy why={why} />
      </div>
    </section>
  );
}

export default AIInsightCard;
