import React from 'react';

const confidenceColors = {
  high: 'bg-green-100 text-green-800',
  medium: 'bg-yellow-100 text-yellow-800',
  low: 'bg-red-100 text-red-800',
};

function AIInsightCard({ type, summary, confidence, why, ExplainWhy }) {
  const { AIBadge } = require('./AIBadge');
  return (
    <section
      className="border rounded-lg shadow-sm p-5 bg-white transition-all duration-300"
      role="region"
      aria-label="AI-generated insight card"
      tabIndex={0}
    >
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <AIBadge label="AI-generated" tooltip="This insight is generated by AI." />
          <span
            className="text-sm font-semibold text-blue-700 uppercase tracking-wide"
            id="ai-insight-label"
          >
            AI Insight
          </span>
        </div>
        <span
          className={`px-2 py-1 rounded text-xs font-medium ${confidenceColors[confidence] || 'bg-gray-100 text-gray-700'}`}
          aria-label={`Confidence: ${confidence}`}
        >
          Confidence: {confidence.charAt(0).toUpperCase() + confidence.slice(1)}
        </span>
      </div>
      <div className="mb-2">
        <span className="font-bold" aria-label="Insight type">
          {type}
        </span>
        <p className="mt-1 text-gray-800" aria-live="polite">
          {summary}
        </p>
      </div>
      <div aria-label="AI insight context">
        <ExplainWhy why={why} />
      </div>
      <div className="italic text-gray-600 text-xs mt-3" aria-label="Advisory disclaimer">
        <strong>For advisory purposes only.</strong> This insight is provided to support
        professional decision-making and does not trigger any actions or changes. Please review the
        context and consult with your team as needed.
      </div>
    </section>
  );
}

export default AIInsightCard;
