import React from 'react';
import PropTypes from 'prop-types';

/**
 * Displays a read-only AI suggestion with all required fields and safe labeling.
 */
export function AISuggestionCard({ suggestion }) {
  if (!suggestion) {
    // Visually hidden for accessibility, avoids blank render
    return <span className="sr-only">No suggestion available</span>;
  }
  const { AIBadge } = require('./AIBadge');
  return (
    <section
      className="border rounded p-4 bg-gray-50 shadow transition-all duration-300"
      role="region"
      aria-label="AI-generated suggestion card"
      tabIndex={0}
    >
      <div className="flex items-center gap-2 mb-2">
        <AIBadge label="AI-generated" tooltip="This recommendation is generated by AI." />
        <span className="text-xs font-semibold text-blue-700" id="ai-suggestion-label">
          Advisory Recommendation
        </span>
      </div>
      <div className="mb-1">
        <strong aria-label="Confidence">Confidence:</strong>{' '}
        {Math.round(suggestion.confidence * 100)}%
      </div>
      <div className="mb-1">
        <strong aria-label="Severity">Severity:</strong>{' '}
        {suggestion.severity.charAt(0).toUpperCase() + suggestion.severity.slice(1)}
      </div>
      <div className="mb-1">
        <strong aria-label="Related Entity">Related Entity:</strong> {suggestion.relatedEntity}
      </div>
      <div className="mb-2" aria-live="polite">
        <strong aria-label="Explanation">Explanation:</strong> {suggestion.explanation}
      </div>
      <div className="italic text-gray-600 text-xs mt-2" aria-label="Advisory disclaimer">
        <strong>For advisory purposes only.</strong> This recommendation is provided to support
        professional decision-making and does not trigger any actions or changes. Please review the
        context and consult with your team as needed.
      </div>
    </section>
  );
}

AISuggestionCard.propTypes = {
  suggestion: PropTypes.shape({
    confidence: PropTypes.number.isRequired,
    explanation: PropTypes.string.isRequired,
    severity: PropTypes.oneOf(['low', 'medium', 'high']).isRequired,
    relatedEntity: PropTypes.string.isRequired,
    advisory: PropTypes.bool.isRequired,
  }),
};
