import React from 'react';
import PropTypes from 'prop-types';
import { AIBadge } from './AIBadge';
import AISeverityPill from './AISeverityPill';
import AIMetadataLine from './AIMetadataLine';
import { formatDate, truncateText } from '../lib/utils/formatting';

/**
 * Displays a read-only AI suggestion with all required fields and safe labeling.
 */
export function AISuggestionCard({ suggestion }) {
  if (!suggestion) {
    // Visually hidden for accessibility, avoids blank render
    return <span className="sr-only">No suggestion available</span>;
  }
  const summaryText = truncateText(
    suggestion.summary || suggestion.explanation || 'Review this recommendation.',
    120,
  );
  const confidence =
    typeof suggestion.confidence === 'number' ? Math.round(suggestion.confidence * 100) : null;
  const formatTimeframe = (value) => {
    if (!value) {
      return 'Not available';
    }
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) {
      return 'Not available';
    }
    return formatDate(date);
  };
  const sourceHint = `${suggestion.type || ''} ${suggestion.relatedEntity || ''} ${suggestion.summary || ''}`
    .toLowerCase()
    .trim();
  const dataSource = suggestion.dataSource
    || (sourceHint.includes('invoice')
      ? 'Invoices'
      : sourceHint.includes('expense')
        ? 'Expenses'
        : sourceHint.includes('transaction') || sourceHint.includes('bank')
          ? 'Bank transactions'
          : 'Accounting data');
  const lastEvaluated =
    suggestion.lastEvaluated ||
    suggestion.lastUpdated ||
    suggestion.updatedAt ||
    suggestion.createdAt ||
    suggestion.timestamp;
  const timeframe =
    suggestion.timeframe || lastEvaluated || suggestion.window || suggestion.timeRange || null;
  return (
    <section
      className="border rounded-lg p-5 bg-white shadow-sm transition-all duration-300"
      role="region"
      aria-label="AI-generated suggestion card"
      tabIndex={0}
    >
      <div className="flex items-center justify-between gap-2 mb-2">
        <div className="flex items-center gap-2">
          <AIBadge label="AI-generated" tooltip="This recommendation is generated by AI." />
          <span className="text-xs font-semibold text-blue-700" id="ai-suggestion-label">
            AI Insight
          </span>
        </div>
        <AISeverityPill severity={suggestion.severity} />
      </div>
      <div className="mb-2 flex flex-wrap items-center gap-3 text-xs text-gray-600">
        <span aria-label="Confidence">
          <strong>Confidence:</strong> {confidence !== null ? `${confidence}%` : 'Not available'}
        </span>
        <span aria-label="Related Entity">
          <strong>Related:</strong> {suggestion.relatedEntity || 'Record'}
        </span>
        <span aria-label="Timeframe">
          <strong>Timeframe:</strong> {formatTimeframe(timeframe)}
        </span>
      </div>
      <div className="mb-2" aria-live="polite">
        <strong aria-label="Rationale">Rationale:</strong>{' '}
        {suggestion.explanation || suggestion.rationale || 'Review this recommendation.'}
      </div>
      <AIMetadataLine
        whyMatters={summaryText}
        dataSource={dataSource}
        lastEvaluated={lastEvaluated}
      />
    </section>
  );
}

AISuggestionCard.propTypes = {
  suggestion: PropTypes.shape({
    id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    type: PropTypes.string,
    confidence: PropTypes.number,
    confidenceScore: PropTypes.number,
    explanation: PropTypes.string,
    rationale: PropTypes.string,
    severity: PropTypes.oneOf(['low', 'medium', 'high', 'unknown']),
    relatedEntity: PropTypes.string,
    entityId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    advisory: PropTypes.bool,
    dataSource: PropTypes.string,
    timeframe: PropTypes.oneOfType([PropTypes.string, PropTypes.number, PropTypes.instanceOf(Date)]),
    lastEvaluated: PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.number,
      PropTypes.instanceOf(Date),
    ]),
  }),
};
