module.exports = {
  admin: {
    allow: ['*'],
  },

  accountant: {
    allow: [
      'GET /health',
      'GET /ready',
      'GET /api/auth/me',
      'POST /api/auth/logout',
      'POST /api/auth/refresh',

      'GET /api/companies',
      'GET /api/dashboard/stats',
      'GET /api/review-center/summary',

      'GET /api/invoices',
      'GET /api/invoices/:id',
      'GET /api/invoices/:id/audit-log',
      'GET /api/invoices/:id/payments',
      'POST /api/invoices',
      'PUT /api/invoices/:id',
      'PATCH /api/invoices/:id/status',
      'POST /api/invoices/:id/payments',
      'POST /api/invoices/:id/credit-note',
      'POST /api/invoice-import/preview',
      'POST /api/invoice-import/commit',

      'GET /api/expenses',
      'GET /api/expenses/:id',
      'POST /api/expenses',
      'POST /api/expenses/:id/posting-preview',
      'POST /api/expenses/:id/post',
      'PATCH /api/expenses/:id/status',

      'GET /api/journal-entries',
      'GET /api/reports/trial-balance',
      'GET /api/reports/profit-loss',
      'GET /api/reports/balance-sheet',
      'GET /api/reports/general-ledger',
      'GET /api/reports/account-ledger',
      'GET /api/reports/vat-summary',
      'GET /api/reports/export',
      'GET /api/journal-entries/export',
      'GET /api/journal-entries/:id',
      'GET /api/journal-entries/:id/audit-log',
      'POST /api/journal-entries/:id/reverse',
      'POST /api/journal-entries/*/reverse',

      'GET /api/bank-statements',
      'GET /api/bank-statements/:id',
      'GET /api/bank-statements/:id/transactions',
      'GET /api/bank-statements/:id/audit-logs',
      'POST /api/bank-statements/import',
      'POST /api/bank-statements/import/confirm',
      'POST /api/bank-statements/reconcile',
      'POST /api/bank-statements/transactions/:id/reconcile',
      'POST /api/bank-statements/transactions/:id/reconcile/undo',
      'PUT /api/bank-statements/transactions/:id/categorize',

      'GET /api/ai/read/*',
      'GET /api/ai/approval-queue',
      'POST /api/ai/approval-queue/approve',
      'POST /api/ai/approval-queue/reject',
      'POST /api/ai/read/*',
      'GET /api/ai/insights',
      'POST /api/ai/voice/assistant',
      'POST /api/ocr/intake/analyze',
      'GET /api/ocr/intake/documents',
      'GET /api/ocr/search',
      'POST /api/ocr/process',
      'GET /api/ocr/results/:id',
      'GET /api/ocr/validate/:id',

      'GET /api/exports/*',
      'GET /api/compliance/*',
      'GET /api/tax-reports/*',
      'GET /api/tax-bridge/readiness',
      'POST /api/tax-reports/*',
    ],
  },

  auditor: {
    allow: [
      'GET /health',
      'GET /ready',
      'GET /api/auth/me',
      'POST /api/auth/logout',

      'GET /api/companies',
      'GET /api/dashboard/stats',
      'GET /api/review-center/summary',

      'GET /api/invoices',
      'GET /api/invoices/:id',
      'GET /api/invoices/:id/audit-log',
      'GET /api/invoices/:id/payments',
      'GET /api/expenses',
      'GET /api/expenses/:id',
      'GET /api/journal-entries',
      'GET /api/reports/trial-balance',
      'GET /api/reports/profit-loss',
      'GET /api/reports/balance-sheet',
      'GET /api/reports/general-ledger',
      'GET /api/reports/account-ledger',
      'GET /api/reports/vat-summary',
      'GET /api/reports/export',
      'GET /api/journal-entries/export',
      'GET /api/journal-entries/:id',
      'GET /api/journal-entries/:id/audit-log',
      'GET /api/bank-statements',
      'GET /api/bank-statements/:id',
      'GET /api/bank-statements/:id/transactions',
      'GET /api/bank-statements/:id/audit-logs',

      'GET /api/ai/insights',
      'POST /api/ai/voice/assistant',
      'GET /api/ai/read/*',
      'GET /api/ai/approval-queue',
      'GET /api/ocr/intake/documents',
      'GET /api/ocr/search',
      'GET /api/ocr/results/:id',
      'GET /api/ocr/validate/:id',
      'POST /api/ai/read/*',

      'GET /api/exports/*',
      'GET /api/compliance/*',
      'GET /api/tax-reports/*',
      'GET /api/tax-bridge/readiness',
    ],
  },

  viewer: {
    allow: [
      'GET /health',
      'GET /ready',
      'GET /api/auth/me',
      'POST /api/auth/logout',

      'GET /api/companies',
      'GET /api/dashboard/stats',
      'GET /api/review-center/summary',
      'GET /api/invoices',
      'GET /api/invoices/:id',
      'GET /api/invoices/:id/audit-log',
      'GET /api/invoices/:id/payments',
      'GET /api/expenses',
      'GET /api/expenses/:id',
      'GET /api/journal-entries',
      'GET /api/reports/trial-balance',
      'GET /api/reports/profit-loss',
      'GET /api/reports/balance-sheet',
      'GET /api/reports/general-ledger',
      'GET /api/reports/account-ledger',
      'GET /api/reports/vat-summary',
      'GET /api/tax-bridge/readiness',
      'GET /api/compliance/*',
      'GET /api/journal-entries/:id',
      'GET /api/journal-entries/:id/audit-log',

      'GET /api/telemetry/client-error',
      'GET /api/ai/insights',
      'POST /api/ai/voice/assistant',
      'GET /api/ai/read/*',
      'GET /api/ai/approval-queue',
      'GET /api/ocr/intake/documents',
      'GET /api/ocr/search',
      'GET /api/ocr/results/:id',
      'GET /api/ocr/validate/:id',
      'POST /api/ai/read/*',
    ],
  },
};
